### ISSUE TITLE
Doc error for Persistence

### ISSUE THREAD

**Issue by AntoninHL** [OpenCTI-Platform/opencti#100]
Seems that there is an error for **persistence** configuration.

Doc says:
```
  elasticsearch:
    [...]
    volumes:
      - esdata:/usr/share/elasticsearch/data

  grakn:
    [...]
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
```

But there is an error at start...
So it must be:

```
  elasticsearch:
    [...]
    volumes:
      - "/usr/share/elasticsearch/data"

  grakn:
    [...]
    volumes:
      - "/grakn-core-all-linux/server/db"
```

**Comment by SamuelHassine** [comment]
@weSh: the documentation seems to be correct according the Docker documentation. But `grakndata` and `esdata` have to be valid path on your host.

For instance:
```
    volumes:
      - /var/lib/grakn:/grakn-core-all-linux/server/db
```

Have you check that?

**Comment by AntoninHL** [comment]
Thanks for your reply !
Ok pour grakn, but what about elastic?

**Comment by SamuelHassine** [comment]
Same thing:
```
    volumes:
      - /var/lib/elastic:/usr/share/elasticsearch/data
```
But just be sure that `/var/lib/elastic` and `/var/lib/grakn` have been created on your host.

**Comment by AntoninHL** [comment]
Fine.
So now, it seems to be ok on this part.
But I have a new error:

`elasticsearch: forward host lookup failed: Unknown host`

and systems is unable to start.

And I checked, elastic hostname is defined:

```
environment:
      [...]
      - ELASTICSEARCH__HOSTNAME=elasticsearch
      - ELASTICSEARCH__PORT=9200
```

Really strange...

**Comment by AntoninHL** [comment]
I removed "volumes" instruction for elastic and it works now... :-(

**Comment by SamuelHassine** [comment]
@weSh: we fix a typo in the `docker-compose.yml` indentation. Could you please pull the repository and try again with persistence? I should work. Thanks!

**Comment by AntoninHL** [comment]
Hey Samuel,

Same player plays again...

Same error:
```
opencti_1        | Waiting ElasticSearch to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
opencti_1        | elasticsearch: forward host lookup failed: Unknown host
```

:-(

**Comment by SamuelHassine** [comment]
@weSh: could you please paste here your full `docker-compose.yml` file? I will try on my side.

**Comment by AntoninHL** [comment]
```
version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.6
    ports:
      - 48555:48555
    volumes:
      - /var/lib/grakn:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - /var/lib/elastic:/usr/share/elasticsearch/data
    restart: always
  rabbitmq:
    image: rabbitmq
    restart: always
  worker:
    image: opencti/worker
    environment:
      - RUN_USER=root
      - OPENCTI_PORT=8080
    volumes:
      - "./config:/opt/opencti/shared_config:rw"
    depends_on:
      - opencti
    links:
      - opencti:opencti
    restart: always
  integration:
    image: opencti/integration
    environment:
      - RUN_USER=root
      - OPENCTI_PORT=8080
    volumes:
      - "./config:/opt/opencti/shared_config:rw"
    depends_on:
      - opencti
    links:
      - opencti:opencti
    restart: always    
  opencti:
    image: opencti/platform
    environment:
      - RUN_USER=root
      - APP__PORT=8080
      - APP__LOGS=./logs
      - APP__CONNECTORS=./integration/connectors
      - APP__SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__HOSTNAME=elasticsearch
      - ELASTICSEARCH__PORT=9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
    ports:
      - "8080:8080"
    volumes:
      - "./config:/opt/opencti/shared_config:rw"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - rabbitmq
    links:
     - grakn:grakn
     - redis:redis
     - elasticsearch:elasticsearch
     - rabbitmq:rabbitmq
    restart: always
```

**Comment by SamuelHassine** [comment]
@weSh: could you please edit your post and paste the file within a code block for indentation?

**Comment by AntoninHL** [comment]
@SamuelHassine done mate!

**Comment by SamuelHassine** [comment]
@weSh: I just pushed to the `master` branch of the repository a working `docker-compose.yml` with the volumes. Just pull the repository and `docker-compose up`. This should work :)

**Comment by AntoninHL** [comment]
:-(

```
elasticsearch_1  | [2019-07-02T08:49:43,342][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
elasticsearch_1  |      at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectory(Files.java:692) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createAndCheckIsDirectory(Files.java:799) ~[?:?]
elasticsearch_1  |      at java.nio.file.Files.createDirectories(Files.java:785) ~[?:?]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.7.1.jar:6.7.1]
elasticsearch_1  |      ... 6 more
worker_1         | Waiting OpenCTI GraphQL to launch...
```

...

```
openctidocker_elasticsearch_1 exited with code 1
worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...
opencti_1        | elasticsearch: forward host lookup failed: Unknown host
opencti_1        | Waiting ElasticSearch to launch...
worker_1         | Waiting OpenCTI GraphQL to launch...
integration_1    | Waiting OpenCTI GraphQL to launch...

```

**Comment by SamuelHassine** [comment]
@weSh: check if the docker user has access to the `./volumes/esdata`, this is a problem of permission.

**Comment by AntoninHL** [comment]
Strange... permission seems ok.

```
grakn:
[...]
    volumes:
      - ./volumes/grakndata:/grakn-core-all-linux/server/db
    
  elasticsearch:
[...]
    volumes:
      - ./volumes/esdata:/usr/share/elasticsearch/data
```
    
at the end of the file, I added:
```
volumes:
  grakndata:
    driver: local
  esdata:
    driver: local
```

Volumes are created in /var/lib/docker/volumes.

`drwx--xr-x 31 1000 1000  4096 juil.  2 09:33 volumes
`
in volumes:
```
drwxr-xr-x  3 1000 1000  4096 juil.  2 09:20 openctidocker_esdata
drwxr-xr-x  3 1000 1000  4096 juil.  2 09:20 openctidocker_grakndata
```
