### ISSUE TITLE
Data collected can't be found by OpenCTI, but still present into the ES database

### ISSUE THREAD

**Issue by toshiro92** [OpenCTI-Platform/opencti#1033]
## Description

I am having an issue with OpenCTI since version `4.0.2`: After few weeks of data collection, OpenCTI is unable to retrieve the data previously collected. I tried to resolve this issue by rebuilding from scratch to the version `4.0.7`, but I had again this issue.

## Environment

1. OS (where OpenCTI server runs): Tried on Ubuntu 18.04 (for the version 4.0.2) and 20.04 (For the version 4.0.7)
2. OpenCTI version: { e.g. OpenCTI 1.0.2 } 4.0.2 & 4.0.7
3. OpenCTI client: { e.g. frontend or python } frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Setup OpenCTI
2. Wait few weeks until the partition has more than 100GB
3. Open OpenCTI GUI and see that all entities disappeared:
![image](https://user-images.githubusercontent.com/17139715/106114449-d9d72b80-614f-11eb-914c-8136ab3facc6.png)

Elasticsearch shows that the index has a quite amount of documents stored:
![image](https://user-images.githubusercontent.com/17139715/106116362-1c016c80-6152-11eb-8d13-590892e5a8cf.png)

And `df -m` command shows that the Docker disk for Elasticsearch is quite big:
```
host@OpenCTI:/var/lib/docker$ df -m /srv/docker/esdata
Filesystem     1M-blocks   Used Available Use% Mounted on
/dev/sda2         257398 179811     66855  73% /
```

And Portainer shows that the container is based on the right Volume path:
![image](https://user-images.githubusercontent.com/17139715/106115780-69310e80-6151-11eb-8811-6b8e409f6f1a.png)

And RabbitMQ indicates that it already treated more than 9M of messages:
![image](https://user-images.githubusercontent.com/17139715/106120451-b19efb00-6156-11eb-9ccc-8a6489a2fb45.png)

## Expected Output

OpenCTI should retrieve all data previously collected.

## Actual Output

OpenCTI is unable to retrieve data previously collected.
 
## Additional information

I do not understand why Elasticsearch takes so much place on disk, as indices in Elasticsearch do not seems to be so heavy.

**Comment by toshiro92** [comment]
Here is also my `docker-compose.yml` configuration regarding Elasticsearch:
```
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: opencti_elasticsearch
    container_name: opencti_elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.seed_hosts=opencti_es02,opencti_es03
      - cluster.initial_master_nodes=opencti_elasticsearch,opencti_es02,opencti_es03
      - cluster.name=es-docker-cluster
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: opencti_es02
    container_name: opencti_es02
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    environment:
      - discovery.seed_hosts=opencti_elasticsearch,opencti_es03
      - cluster.initial_master_nodes=opencti_elasticsearch,opencti_es02,opencti_es03
      - cluster.name=es-docker-cluster
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    hostname: opencti_es03
    container_name: opencti_es03
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    environment:
      - discovery.seed_hosts=opencti_elasticsearch,opencti_es02
      - cluster.initial_master_nodes=opencti_elasticsearch,opencti_es02,opencti_es03
      - cluster.name=es-docker-cluster
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
[...]
volumes:
  esdata:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/docker/esdata
  esdata2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/docker/esdata2
  esdata3:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/docker/esdata3
```
