### ISSUE TITLE
Connectors fail to connect to OpenCTI API

### ISSUE THREAD

**Issue by nov3mb3r** [OpenCTI-Platform/opencti#1061]
## Description
Connectors fail to connect to OpenCTI API

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.10
2. OpenCTI version: OpenCTI 4.1.2

## Reproducible Steps

1. Downloaded the VM for version 4.1.2 from the Luatix Google Drive folder
2. checked access and then proceeded in downloading and enabling connectors.
3. Downloaded the connectors for version 4.1.2 and proceeded enabling CVE connector exactly following the steps in the respective read.me. The problem appears when running 'sudo docker-compose up', the connectors fail to connect

## Actual Output

```
OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
```
 
## Additional information
cve connector's docker-compose file
```
version: '3'
services:
  connector-cve:
    image: opencti/connector-cve:4.1.2
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=[user-token-from settings>accesses]
      - CONNECTOR_ID=20348127-4083-49d2-ad35-91b558b93ab6 
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Common Vulnerabilities and Exposures
      - CONNECTOR_SCOPE=identity,vulnerability
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CVE_IMPORT_HISTORY=true # Import history at the first run (after only recent), reset the connector state if you want to re-import
      - CVE_NVD_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-recent.json.gz
      - CVE_HISTORY_DATA_FEED=https://nvd.nist.gov/feeds/json/cve/1.1/
      - CVE_INTERVAL=7 # In days, must be strictly greater than 1
    restart: always
```

**Comment by richard-julien** [comment]
In docker if you start your containers in different docker compose they cant directly talk to each others. You need to start the connector in the same docker compose or configure your docker network to let containers access each others.

**Comment by nov3mb3r** [comment]
Ah I found the problem! Is there any way to do it from the Portainer interface? Below is my current configuration. Should they be in the same network as the bridge (system)? Also should the ownership change to public?
![image](https://user-images.githubusercontent.com/10418973/107236654-94a7d900-6a2e-11eb-8799-b8a90bb60073.png)

**Comment by Ken-Abruzzi** [comment]
> In docker if you start your containers in different docker compose they cant directly talk to each others. You need to start the connector in the same docker compose or configure your docker network to let containers access each others.



> In docker if you start your containers in different docker compose they cant directly talk to each others. You need to start the connector in the same docker compose or configure your docker network to let containers access each others.

Hello. Do you mean I have to combine all services (like cve-connector, platform, redis, rabbitmq, etc.) in only one docker-compose.yml file??? Thank you! @richard-julien

**Comment by paulzroe** [comment]
What works for me is adding the following in your  connector's docker-compose.yml. This means you are connecting your connector to the same network where opencti is, which in my case is docker_default.

```
    networks:
      - docker_default

networks:
  docker_default:
    external: true
```
