### ISSUE TITLE
Question for AlienVault Connectors

### ISSUE THREAD

**Issue by fareedfauzi** [OpenCTI-Platform/opencti#1192]
Is it normal the AlienVault connector produces so many workers and still does not complete any of it since yesterday I run the `docker-compose up` ?
![image](https://user-images.githubusercontent.com/56353946/112243955-74a04200-8c89-11eb-9cd4-e3448a437e44.png)

The output of my `docker-compose up` since yesterday...

```
connector-alienvault_1  | ERROR:pika.adapters.utils.selector_ioloop_adapter:Address resolution failed: gaierror(-2, 'Name does not resolve')
connector-alienvault_1  | ERROR:pika.adapters.utils.connection_workflow:getaddrinfo failed: gaierror(-2, 'Name does not resolve').
connector-alienvault_1  | ERROR:pika.adapters.utils.connection_workflow:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None.
connector-alienvault_1  | ERROR:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None
connector-alienvault_1  | ERROR:pika.adapters.blocking_connection:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None
connector-alienvault_1  | ERROR:pika.adapters.blocking_connection:Error in _create_connection().
connector-alienvault_1  | Traceback (most recent call last):
connector-alienvault_1  |   File "/usr/local/lib/python3.8/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
connector-alienvault_1  |     raise self._reap_last_connection_workflow_error(error)
connector-alienvault_1  |   File "/usr/local/lib/python3.8/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
connector-alienvault_1  |     result = socket.getaddrinfo(self._host, self._port, self._family,
connector-alienvault_1  |   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
connector-alienvault_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
connector-alienvault_1  | socket.gaierror: [Errno -2] Name does not resolve
connector-alienvault_1  | ERROR:root:Internal error: [Errno -2] Name does not resolve
connector-alienvault_1  | INFO:root:Running AlienVault connector...
connector-alienvault_1  | INFO:root:Loaded state: {}
connector-alienvault_1  | INFO:root:Connector first run
connector-alienvault_1  | INFO:root:Initiate work for fd4cc1fd-6f2c-412e-8928-0ae942311450
connector-alienvault_1  | INFO:root:Running pulse importer (update data: False, guess malware: False, guess cve: False).
```

Alienvault docker-compose.yml
```
version: '3'
services:
  connector-alienvault:
    image: opencti/connector-alienvault:4.3.1
    environment:
      - OPENCTI_URL=http://192.168.8.104:8080
      - OPENCTI_TOKEN=925c5480-9d0a-46ab-b111-218478a0e095
      - CONNECTOR_ID=fd4cc1fd-6f2c-412e-8928-0ae942311450
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=AlienVault
      - CONNECTOR_SCOPE=alienvault
      - CONNECTOR_CONFIDENCE_LEVEL=15
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - ALIENVAULT_BASE_URL=https://otx.alienvault.com
      - ALIENVAULT_API_KEY=9e549667884479b18bdeef6d1696e61fd3ccf7cf86da95e7600fe2841c2b0bdf
      - ALIENVAULT_TLP=White
      - ALIENVAULT_CREATE_OBSERVABLES=true
      - ALIENVAULT_CREATE_INDICATORS=true
      - ALIENVAULT_PULSE_START_TIMESTAMP=2020-05-01T00:00:00                  # BEWARE! Could be a lot of pulses!
      - ALIENVAULT_REPORT_TYPE=threat-report
      - ALIENVAULT_REPORT_STATUS=New
      - ALIENVAULT_GUESS_MALWARE=false                                        # Use tags to guess malware.
      - ALIENVAULT_GUESS_CVE=false                                            # Use tags to guess CVE.
      - ALIENVAULT_EXCLUDED_PULSE_INDICATOR_TYPES=FileHash-MD5,FileHash-SHA1  # Excluded Pulse indicator types.
      - ALIENVAULT_INTERVAL_SEC=1800
    restart: always
```
