### ISSUE TITLE
Is there an example of SAML authentication?

### ISSUE THREAD

**Issue by bLackCat-79** [OpenCTI-Platform/opencti#1458]
In the docs I only find a sample of AD/LDAP authentication to use with docker.
I would like to do it with SAML

**Comment by SamuelHassine** [comment]
Hello,

https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a.

![image](https://user-images.githubusercontent.com/1334279/125285323-d4932500-e31a-11eb-96a8-31fb6382ecbc.png)

https://www.notion.so/luatix/Configuration-a568604c46d84f39a8beae141505572a#36e6d29c4a7f47b0b89849bd16e6ea84.

Kind regards,
Samuel

**Comment by bLackCat-79** [comment]
@SamuelHassine I have read this, but how do I add it to my docker config?

Like this?:

- PROVIDERS__SAML__STRATEGY=OpenIDConnectStrategy 
- "PROVIDERS__SAML__CONFIG__LABEL=Login with SAML"
- PROVIDERS__SAML__CONFIG__ISSUER=https://xxxxxxx/auth/realms/xxxx
- PROVIDERS__SAML__CONFIG__CLIENT_ID=XXXXXXXXXXXXXXXXXX
- PROVIDERS__SAML__CONFIG__CLIENT_SECRET=XXXXXXXXXXXXXXXXXX
- "PROVIDERS__SAML__CONFIG__REDIRECT_URIS=[\"https://demo.opencti.io/auth/oic/callback\"]"

**Comment by bLackCat-79** [comment]
@anyone?

**Comment by nor3th** [comment]
Add them to the opencti environment variables. Like this:

```
  opencti:
    image: opencti/platform:4.5.5
    environment:
      - NODE_OPTIONS=--max-old-space-size=8096
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=${OPENCTI_ADMIN_TOKEN}
      - APP__APP_LOGS__LOGS_LEVEL=error
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO_SECRET_KEY}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - PROVIDERS__SAML__STRATEGY=OpenIDConnectStrategy
      - "PROVIDERS__SAML__CONFIG__LABEL=Login with SAML"
      - PROVIDERS__SAML__CONFIG__ISSUER=https://xxxxxxx/auth/realms/xxxx
      - PROVIDERS__SAML__CONFIG__CLIENT_ID=XXXXXXXXXXXXXXXXXX
      - PROVIDERS__SAML__CONFIG__CLIENT_SECRET=XXXXXXXXXXXXXXXXXX
      - "PROVIDERS__SAML__CONFIG__REDIRECT_URIS=["https://demo.opencti.io/auth/oic/callback"]"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
```
