### ISSUE TITLE
OpenCTI should be able to use password with only numbers in it

### ISSUE THREAD

**Issue by Serrvosky** [OpenCTI-Platform/opencti#208]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I just start OpenCTI by docker installation, and when I try to login it fails giving this response:

`{"errors":[{"message":"Wrong name or password","name":"AuthenticationFailure","time_thrown":"2019-09-04T13:22:03.470Z","data":{"type":"business"}}],"data":{"token":null}}
`
I change docker-compose file env vars: 
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=123123123

I
## Environment

1. Ubuntu Server
2. OpenCTI version: 1.1.1
3. OpenCTI client: ??
4. Other environment details:

## Reproducible Steps
Steps to create the smallest reproducible scenario:
All the step indicated in the documentation:
https://opencti-platform.github.io/docs/installation/docker

## Expected Output

Success on login page

## Actual Output

Failed login

**Comment by richard-julien** [comment]
Really strange error. Can you attach your docker compose file on this ticket?

**Comment by Serrvosky** [comment]
```
version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.5.7
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    restart: always
  opencti:
    image: opencti/platform:1.1.1
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=123123123
      - APP__ADMIN__TOKEN=de42fdb8-267b-499f-b9bf-77be0d286dde
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    ports:
      - "8080:8080"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - rabbitmq
    restart: always
  worker-import:
    image: opencti/worker:1.1.1
    environment:
      - WORKER_TYPE=import
      - WORKER_LOG_LEVEL=info
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=de42fdb8-267b-499f-b9bf-77be0d286dde
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PORT_MANAGEMENT=15672
      - RABBITMQ_MANAGEMENT_SSL=false
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 4
    restart: always
  worker-export:
    image: opencti/worker:1.1.1
    environment:
      - WORKER_TYPE=export
      - WORKER_LOG_LEVEL=info
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=de42fdb8-267b-499f-b9bf-77be0d286dde
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_PORT_MANAGEMENT=15672
      - RABBITMQ_MANAGEMENT_SSL=false
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 2      
    restart: always
  connector-opencti:
    image: opencti/connector-opencti:1.1.2
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672 
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - OPENCTI_NAME=OpenCTI
      - OPENCTI_CONFIDENCE_LEVEL=5
      - OPENCTI_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - OPENCTI_ENTITIES=identity,sector,region,country,city
      - OPENCTI_INTERVAL=1 # Days
      - OPENCTI_LOG_LEVEL=info
    depends_on:
      - opencti
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:1.1.2
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672 
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MITRE_NAME=MITRE\ ATT&CK
      - MITRE_CONFIDENCE_LEVEL=3
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_ENTITIES=identity,attack-pattern,course-of-action,intrusion-set,malware,tool
      - MITRE_INTERVAL=7 # Days
      - MITRE_LOG_LEVEL=info    
    depends_on:
      - opencti
    restart: always            
volumes:
  grakndata:
  esdata:
```
