### ISSUE TITLE
MISP manifest for connector not found

### ISSUE THREAD

**Issue by mathurin68** [OpenCTI-Platform/opencti#222]
Last Question for awhile I promise trying to get this working...

It's on an Ubuntu 18 box, which also hosts MISP

```
money@MISP:/opt/opencti/docker$ sudo docker pull opencti/connector-misp
Using default tag: latest
latest: Pulling from opencti/connector-misp
Digest: sha256:223d9e715b482532713f833de918618a05358a7dd35e865397c3de4d312aabfb
Status: Image is up to date for opencti/connector-misp:latest
```
added this connector to the docker-compose.yml 
*https://opencti-platform.github.io/docs/installation/connectors
```
  connector-misp:
    image: opencti/connector-misp:2.4.116
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - MISP_NAME=MISP\ Circle
      - MISP_CONFIDENCE_LEVEL=3
      - MISP_URL=https://misp.org.net
      - MISP_KEY=ourkey
      - MISP_TAG=OpenCTI:\ Import
      - MISP_UNTAG_EVENT=true
      - MISP_IMPORTED_TAG=OpenCTI:\ Imported
      - MISP_INTERVAL=1 # Minutes
      - MISP_LOG_LEVEL=info
    restart: always
```

```
money@MISP:/opt/opencti/docker$ sudo docker-compose up
Pulling connector-misp (opencti/connector-misp:2.4.116)...
ERROR: manifest for opencti/connector-misp:2.4.116 not found
```

Is this version of MISP(latest) not supported?  

Thanks!
