### ISSUE TITLE
Grakn Seems Down 

### ISSUE THREAD

**Issue by jemoussaoui** [OpenCTI-Platform/opencti#547]
Environment : 
   - Debian 10
   - OpenCTI 3.0.2

Problem : 
```
  error: [GRAKN] Seems down                                                                                                  
   error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
```

**Comment by richard-julien** [comment]
Hi @jemoussaoui , can you upload here your docker compose, the result of docker ps command, and the logs of the grakn docker + opencti docker.
Thanks

**Comment by jemoussaoui** [comment]
docker-compose.yml

```
`version: '3'
services:
  grakn :
    image: graknlabs/grakn:1.6.2
    ports:
      - 48555:48555 
    volumes :
     - grakndata:/grakn-core-all-linux/server/db
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}    
    restart: always
  opencti:
    image: opencti/platform:latest
    environment:
      - APP__PORT=4000
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=....
      - APP__ADMIN__TOKEN=...
      - APP__LOGS_LEVEL=error
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=...
      - MINIO__SECRET_KEY=...
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:latest
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=...
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:latest
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=...
      - CONNECTOR_ID=... # Valid UUDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:latest
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=..
      - CONNECTOR_ID=.. # Valid UUDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=application/csv
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always    
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:latest
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=...
      - CONNECTOR_ID=.. # Valid UUDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
  connector-import-file-pdf-observables:
    image: opencti/connector-import-file-pdf-observables:latest
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=..
      - CONNECTOR_ID=.. # Valid UUDv4
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFilePdfObservables
      - CONNECTOR_SCOPE=application/pdf
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - PDF_OBSERVABLES_CREATE_INDICATOR=False
    restart: always    
  connector-opencti:
    image: opencti/connector-opencti:latest
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=...
      - CONNECTOR_ID=.. # Valid UUDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=OpenCTI
      - CONNECTOR_SCOPE=identity,sector,region,country,city
      - CONNECTOR_CONFIDENCE_LEVEL=5
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_INTERVAL=7 # Days
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:latest
    environment:
      - OPENCTI_URL=http://localhost:4000
      - OPENCTI_TOKEN=..
      - CONNECTOR_ID=... # Valid UUDv4
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE ATT&CK
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_INTERVAL=7 # Days
    restart: always
volumes:
  grakndata:
  esdata:
  s3data:`
```

docker ps : 

```
CONTAINER ID        IMAGE                                                  COMMAND                  CREATED             STATUS                            PORTS                                                 NAMES
5247ce8f1c57        opencti/connector-mitre:latest                         "/entrypoint.sh"         31 minutes ago      Up 2 seconds                                                                            docker_connector-mitre_1
397ac609e445        opencti/connector-export-file-stix:latest              "/entrypoint.sh"         31 minutes ago      Up 1 second                                                                             docker_connector-export-file-stix_1
9ab251929dd8        docker.elastic.co/elasticsearch/elasticsearch:7.5.2    "/usr/local/bin/dock…"   31 minutes ago      Up 4 seconds                      9200/tcp, 9300/tcp                                    docker_elasticsearch_1
a30910b1809d        opencti/connector-opencti:latest                       "/entrypoint.sh"         31 minutes ago      Up 2 seconds                                                                            docker_connector-opencti_1
d52eeb63c9f5        opencti/connector-import-file-pdf-observables:latest   "/entrypoint.sh"         31 minutes ago      Up 2 seconds                                                                            docker_connector-import-file-pdf-observables_1
d46008d9cc56        minio/minio:RELEASE.2019-10-12T01-39-57Z               "/usr/bin/docker-ent…"   31 minutes ago      Up 3 seconds (health: starting)   0.0.0.0:9000->9000/tcp                                docker_minio_1
19cc71a42d4f        opencti/connector-import-file-stix:latest              "/entrypoint.sh"         31 minutes ago      Up 2 seconds                                                                            docker_connector-import-file-stix_1
b755808efd03        opencti/connector-export-file-csv:latest               "/entrypoint.sh"         31 minutes ago      Up 3 seconds                                                                            docker_connector-export-file-csv_1
8cf74199c90c        graknlabs/grakn:1.6.2                                  "./grakn-docker.sh"      31 minutes ago      Up 4 seconds                      0.0.0.0:48555->48555/tcp                              docker_grakn_1
5f1332de7574        redis:5.0.5                                            "docker-entrypoint.s…"   31 minutes ago      Up 2 seconds                      6379/tcp                                              docker_redis_1
a3bb876a4d08        rabbitmq:3.7.17-management                             "docker-entrypoint.s…"   31 minutes ago      Up 2 seconds                      4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   docker_rabbitmq_1
```





docker logs docker_grakn_1 : 
```

====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
                                                                                      Version: 1.6.2
Starting Storage....FAILED!
Unable to start Storage.
====================================================================================================
      ________  _____     _______  __    __  __    __      _______  _______  _____     _______
     |   __   ||   _  \  |   _   ||  |  /  /|  \  |  |    |   _   ||   _   ||   _  \  |   ____|
     |  |  |__||  | |  | |  | |  ||  | /  / |   \ |  |    |  | |__||  | |  ||  | |  | |  |
     |  | ____ |  |_| /  |  |_|  ||  |/  /  |    \|  |    |  |     |  | |  ||  |_| /  |  |____
     |  ||_   ||   _  \  |   _   ||   _  \  |   _    |    |  |  __ |  | |  ||   _  \  |   ____|
     |  |__|  ||  | \  \ |  | |  ||  | \  \ |  | \   |    |  |_|  ||  |_|  ||  | \  \ |  |____
     |________||__|  \__\|__| |__||__|  \__\|__|  \__|    |_______||_______||__|  \__\|_______|

                                         THE KNOWLEDGE GRAPH
====================================================================================================
                                                                                      Version: 1.6.2

Starting Storage....FAILED!
Unable to start Storage.
```


docker logs docker_opencti_1 : 

```
yarn run v1.19.1
$ node --max_old_space_size=8192 build/index.js
error: [GRAKN] Seems down
error: [OPENCTI] GraphQL initialization fail > Error: Grakn seems down
    at B (/opt/opencti/build/index.js:1:5498)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.19.1
```
