### ISSUE TITLE
connector-diode-import - Container Issue - python3: can't open file '//diode-import.py':

### ISSUE THREAD

**Issue by PeeBee66** [OpenCTI-Platform/opencti#7061]
## Description

When attempting to test the ingestion of data into OpenCTI using the airgapped diode, an error is encountered.

## Environment

1. OS - Ubuntu
2. OpenCTI version: 6.1.3
3. OpenCTI client: 6.1.3
4. Other environment details: docker build

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Deploy CVE, Mandiant, and MITRE and ensure they are making bundles and collecting data in .json format.
2. Copy data to offline environment 
3. Build fresh 6.1.3 opencti (this is working)
4. Using the following import diode connector 
```
  connector-diode-import-mitre:
    image: opencti/connector-diode-import:6.1.3
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=${OPENCTI_MITRE_USER_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MITRE_ID}
      - CONNECTOR_NAME=MitreImport
      - CONNECTOR_RUN_AND_TERMINATE=false
      - CONNECTOR_LOG_LEVEL=debug
      - DIODE_IMPORT_APPLICANT_MAPPINGS=${CONNECTOR_MITRE_ID}:${CONNECTOR_SOURCE_MITRE_ID}
      - DIODE_IMPORT_GET_FROM_DIRECTORY_PATH=/data
      - DIODE_IMPORT_GET_FROM_DIRECTORY_RETENTION=7
    restart: always
    volumes:
      - type: bind
        source: "/mnt/connector/8.Test-Backup/c.test"
        target: /data
```
5. see if it can ingest the data
## Expected Output

Docker Container should start or at least give me a different error

## Actual Output

Encountering an error when trying to cd into the directory and open the diode-import.py file.
