### ISSUE TITLE
 opencti_connector-misp

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/opencti#981]
## Description

{  opencti_connector-misp. is being created then stopped, then a new one is created and stopped and so on. }

## Environment

1. OS (where OpenCTI server runs): { Ubuntu 20.04 / Virtual machine template. }
2. OpenCTI version: { OpenCTI 4.0.3 }

## MISP Connector:
Added configuration:
```
connector-misp:
    image: opencti/connector-misp:latest
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_MISP_ID}
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MISP
      - CONNECTOR_SCOPE=misp
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=info
      - MISP_URL=${CONNECTOR_MISP_URL} # Required
      - MISP_KEY=${CONNECTOR_MISP_API} # Required
      - MISP_SSL_VERIFY=False # Required
      - MISP_CREATE_REPORTS=True # Required, create report for MISP event
      - MISP_REPORT_CLASS=MISP Event # Optional, report_class if creating report for event
      - MISP_IMPORT_FROM_DATE=2000-01-01 # Optional, import all event from this date
      - MISP_IMPORT_TAGS=opencti:import,type:osint # Optional, list of tags used for import events
      - MISP_INTERVAL=1 # Required, in minutes
    restart: always
```

## Environment Variables:
![image](https://user-images.githubusercontent.com/37035465/103708181-1edcc780-4fc1-11eb-82d0-b79136e38133.png)

## Issue:
It keeps creating the docker images and eating diskspace.
![image](https://user-images.githubusercontent.com/37035465/103707935-9fe78f00-4fc0-11eb-922c-3b4998eda207.png)

![image](https://user-images.githubusercontent.com/37035465/103708004-bf7eb780-4fc0-11eb-9dfe-8656156663ea.png)

![image](https://user-images.githubusercontent.com/37035465/103708015-c3123e80-4fc0-11eb-9529-ca9ef6f80ce5.png)

Regards,
Khalid.
